/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./../components/base/AppButton.vue')['default']
    BackButton: typeof import('./../components/navigation/BackButton.vue')['default']
    Breadcrumb: typeof import('./../components/navigation/Breadcrumb.vue')['default']
    ButtonShowcase: typeof import('./../components/editor/ButtonShowcase.vue')['default']
    CommentItem: typeof import('./../components/editor/CommentItem.vue')['default']
    CommentPanel: typeof import('./../components/editor/CommentPanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmptyState: typeof import('./../components/base/EmptyState.vue')['default']
    FlatButton: typeof import('./../components/base/FlatButton.vue')['default']
    GlobalNav: typeof import('./../components/GlobalNav.vue')['default']
    Logo: typeof import('./../components/navigation/Logo.vue')['default']
    PageTransition: typeof import('./../components/navigation/PageTransition.vue')['default']
    PaperInput: typeof import('./../components/base/PaperInput.vue')['default']
    PopCard: typeof import('./../components/base/PopCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StickyNote: typeof import('./../components/base/StickyNote.vue')['default']
    UpgradeModal: typeof import('./../components/UpgradeModal.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
